// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2024-08-05, 9:35:42 p.m.
const configMerger = require("C:/Users/oguad/OneDrive/Desktop/threads/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/Users/oguad/OneDrive/Desktop/threads/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/oguad/OneDrive/Desktop/threads/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/oguad/OneDrive/Desktop/threads/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/oguad/OneDrive/Desktop/threads/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/oguad/OneDrive/Desktop/threads/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/oguad/OneDrive/Desktop/threads/plugins/**/*.{js,ts,mjs}","C:/Users/oguad/OneDrive/Desktop/threads/composables/**/*.{js,ts,mjs}","C:/Users/oguad/OneDrive/Desktop/threads/utils/**/*.{js,ts,mjs}","C:/Users/oguad/OneDrive/Desktop/threads/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/oguad/OneDrive/Desktop/threads/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/oguad/OneDrive/Desktop/threads/app.config.{js,ts,mjs}"] }));

module.exports = config
